# Generated by Django 2.1.1 on 2018-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('telefone', models.CharField(max_length=200, verbose_name='Telefone')),
                ('foto', models.ImageField(upload_to='fotos_anuncios')),
            ],
        ),
    ]
