# Generated by Django 2.1.1 on 2018-09-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='cep',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='cidade',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='telefone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
