# Generated by Django 2.1.1 on 2018-10-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_auto_20180926_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='foto',
            new_name='imagem',
        ),
    ]
