# Generated by Django 2.1.1 on 2018-10-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20181009_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('imagem', models.ImageField(upload_to='catalogo/images/apts')),
                ('descricao', models.TextField(blank=True)),
                ('dono', models.TextField(blank=True)),
                ('preco', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('numero', models.PositiveIntegerField()),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(db_index=True, max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastramento', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('endereco', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete='models.CASCADE', related_name='imoveis', to='catalogo.Category')),
            ],
            options={
                'verbose_name': 'imovel',
                'verbose_name_plural': 'imoveis',
                'ordering': ('cidade',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
