# Generated by Django 2.1.1 on 2018-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_imovel_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(upload_to='catalogo/images'),
        ),
    ]
