# Generated by Django 2.1.1 on 2018-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20181014_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(default='imagens/no-image.png', upload_to='catalogo/imagens/anuncios', verbose_name='Imagem'),
        ),
    ]
