# Generated by Django 2.1.1 on 2018-10-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20181014_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(default='imagens/no-image.png', upload_to='catalogo/media/imagens', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero',
            field=models.CharField(max_length=5),
        ),
    ]
