# Generated by Django 2.1.1 on 2018-10-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20181014_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(default='imagens/no-image.png', upload_to='static/imagem/upload', verbose_name='Imagem'),
        ),
    ]
