# Generated by Django 2.1.1 on 2018-10-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20181028_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(default='imagens/no-image.png', upload_to='media/catalogo/media/imagens', verbose_name='Imagem'),
        ),
    ]
