# Generated by Django 2.1.1 on 2018-10-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20181028_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(upload_to='media/', verbose_name='Imagem'),
        ),
    ]
