# Generated by Django 2.1.1 on 2018-10-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('idade', models.IntegerField(verbose_name='Ex: 30')),
                ('cpf', models.IntegerField(verbose_name='000.000.000-00')),
                ('cep', models.CharField(max_length=8, verbose_name='00000-000')),
                ('cidade', models.CharField(max_length=150, verbose_name='Ex: Rio de Janeiro')),
            ],
        ),
    ]
