# Generated by Django 2.1.1 on 2018-11-01 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('idade', models.IntegerField(verbose_name='Idade:')),
                ('cpf', models.IntegerField(verbose_name='CPF:')),
                ('cidade', models.CharField(blank=True, max_length=150, verbose_name='Cidade:')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP:')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
