# Generated by Django 2.1.1 on 2018-10-15 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('idade', models.IntegerField(verbose_name='Ex: 30')),
                ('cpf', models.IntegerField(verbose_name='000.000.000-00')),
                ('cep', models.CharField(max_length=8, verbose_name='00000-000')),
                ('cidade', models.CharField(max_length=150, verbose_name='Ex: Rio de Janeiro')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
