# Generated by Django 2.1.1 on 2018-10-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181015_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cidade',
            field=models.CharField(max_length=150, verbose_name='Cidade:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idade',
            field=models.IntegerField(verbose_name='Idade:'),
        ),
    ]
