# Generated by Django 2.1.1 on 2018-10-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181016_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cep',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cidade:'),
        ),
    ]
